
INPUT_ONE_HOT_LIMIT = 100
INPUT_BINARY_LIMIT = 20
INPUT_SIZE = 1
OUTPUT_SIZE = 1
HIDDEN_SIZE = 20
DROPOUT_RATE = 0.5
MINIBATCH_SIZE = 32
EPOCHS = 100
TRAINING_PERCENT = 0.8
WEIGHT_INIT = "glorot_normal"

PRETRAINING_EPOCHS = 0

# META_INPUT_SIZE = INPUT_ONE_HOT_LIMIT + HIDDEN_SIZE
META_HIDDEN_SIZE = 32
META_DROPOUT_RATE = 0.5
META_HIST_SIZE = 20
META_HIST_ZERO_PROB = 1e-5
META_NUMBER_MODELS = 10
META_EPOCHS = 1000
META_LEARNING_RATE = 0.0001
META_INPUT_SIZE = INPUT_ONE_HOT_LIMIT + META_HIST_SIZE * HIDDEN_SIZE
META_BATCH_SIZE = 128

META_DATASET_FILENAME = "metacog_dataset.h5"




